-- 统一动态菜单资源与前端路由的展示名称；路径与资源 ID 保持不变，既有角色授权不受影响。
UPDATE sys_resource
SET name       = CASE id
                     WHEN 'menu_agent' THEN 'AI Agent Platform'
                     WHEN 'agent_model_provider' THEN 'Model Providers'
                     WHEN 'agent_definition' THEN 'Agent Configurations'
                     WHEN 'agent_mcp_server' THEN 'MCP Servers'
                     WHEN 'agent_tool' THEN 'Tool Catalog'
                     WHEN 'agent_chat' THEN 'Chat Playground'
                     WHEN 'agent_run' THEN 'Execution History'
                     WHEN 'agent_skill' THEN 'Agent Skills'
                     WHEN 'agent_artifact' THEN 'Generated File Library'
                     WHEN 'agent_sandbox' THEN 'Sandbox Execution Platform'
                     WHEN 'menu_workflow' THEN 'AI Workflows'
                     WHEN 'agent_workflow' THEN 'Workflow Management'
                     WHEN 'agent_workflow_run' THEN 'Workflow Instances'
                     WHEN 'agent_workflow_schedule' THEN 'Scheduled Workflow Tasks'
                     WHEN 'menu_knowledge' THEN 'Knowledge Center'
                     WHEN 'knowledge_base' THEN 'Knowledge Bases'
                     WHEN 'knowledge_document' THEN 'Knowledge Documents'
                     WHEN 'knowledge_reviews' THEN 'Content Review'
                     WHEN 'sys_admin_preference' THEN 'Administrator Preferences'
                     WHEN 'sys_service_account' THEN 'Service Account Management'
                     WHEN 'sys_config' THEN 'System Configuration'
                     WHEN '2' THEN 'Resource & Permission Management'
                     WHEN '5' THEN 'Administrator Management'
                     WHEN '12' THEN 'Dashboard'
                     WHEN '30' THEN 'Email Messages'
                     WHEN '31' THEN 'SMS Messages'
                     ELSE name END,
    name_cn    = CASE id
                     WHEN 'menu_agent' THEN '智能体平台'
                     WHEN 'agent_model_provider' THEN '模型服务商'
                     WHEN 'agent_definition' THEN '智能体配置'
                     WHEN 'agent_mcp_server' THEN 'MCP 服务'
                     WHEN 'agent_tool' THEN '工具目录'
                     WHEN 'agent_chat' THEN '对话调试'
                     WHEN 'agent_run' THEN '执行记录'
                     WHEN 'agent_skill' THEN '智能体技能'
                     WHEN 'agent_artifact' THEN '生成文件库'
                     WHEN 'agent_sandbox' THEN '沙箱执行平台'
                     WHEN 'menu_workflow' THEN 'AI 工作流'
                     WHEN 'agent_workflow' THEN '工作流管理'
                     WHEN 'agent_workflow_run' THEN '工作流实例'
                     WHEN 'agent_workflow_schedule' THEN '工作流定时任务'
                     WHEN 'menu_knowledge' THEN '知识中心'
                     WHEN 'knowledge_base' THEN '知识库'
                     WHEN 'knowledge_document' THEN '知识文档'
                     WHEN 'knowledge_reviews' THEN '内容审核'
                     WHEN 'sys_admin_preference' THEN '管理员偏好'
                     WHEN 'sys_service_account' THEN '服务账号管理'
                     WHEN 'sys_config' THEN '系统配置'
                     WHEN '2' THEN '资源与权限'
                     WHEN '5' THEN '管理员管理'
                     WHEN '12' THEN '工作台'
                     WHEN '30' THEN '邮件消息'
                     WHEN '31' THEN '短信消息'
                     ELSE name_cn END,
    updated_at = (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT
WHERE id IN (
    'menu_agent'
    , 'agent_model_provider'
    , 'agent_definition'
    , 'agent_mcp_server'
    , 'agent_tool'
    , 'agent_chat'
    , 'agent_run'
    , 'agent_skill'
    , 'agent_artifact'
    , 'agent_sandbox'
    , 'menu_workflow'
    , 'agent_workflow'
    , 'agent_workflow_run'
    , 'agent_workflow_schedule'
    , 'menu_knowledge'
    , 'knowledge_base'
    , 'knowledge_document'
    , 'knowledge_reviews'
    , 'sys_admin_preference'
    , 'sys_service_account'
    , 'sys_config'
    , '2'
    , '5'
    , '12'
    , '30'
    , '31'
    )
  AND deleted = FALSE;
