package com.aether.agent.service.impl;
import com.aether.agent.entity.*; import com.aether.agent.mapper.*; import com.aether.agent.service.AgentRunPlanService; import com.aether.agent.vo.AgentRunPlanVo; import com.alibaba.fastjson2.JSON; import com.alibaba.fastjson2.JSONArray; import com.alibaba.fastjson2.JSONObject; import com.baomidou.mybatisplus.core.toolkit.Wrappers; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import java.util.stream.Collectors;
@Service public class AgentRunPlanServiceImpl implements AgentRunPlanService {
 private final AgentRunPlanMapper plans; private final AgentRunPlanVersionMapper versions; private final AgentRunPlanStepMapper steps;
 public AgentRunPlanServiceImpl(AgentRunPlanMapper plans, AgentRunPlanVersionMapper versions, AgentRunPlanStepMapper steps){this.plans=plans;this.versions=versions;this.steps=steps;}
 @Override @Transactional(rollbackFor=Exception.class) public void recordPlan(String runId,String reason,String summary,String snapshot){ long now=System.currentTimeMillis(); AgentRunPlan plan=plans.selectOne(Wrappers.lambdaQuery(AgentRunPlan.class).eq(AgentRunPlan::getRunId,runId)); if(plan==null){plan=new AgentRunPlan();plan.setRunId(runId);plan.setCurrentVersion(0);plans.insert(plan);} int version=(plan.getCurrentVersion()==null?0:plan.getCurrentVersion())+1; AgentRunPlanVersion item=new AgentRunPlanVersion();item.setPlanId(plan.getId());item.setVersion(version);item.setReason(reason);item.setSummary(summary);item.setSnapshot(snapshot);versions.insert(item); JSONArray tasks=JSON.parseObject(snapshot).getJSONArray("tasks"); if(tasks!=null) for(int i=0;i<tasks.size();i++){JSONObject task=tasks.getJSONObject(i);AgentRunPlanStep step=new AgentRunPlanStep();step.setPlanVersionId(item.getId());step.setStepKey(task.getString("id"));step.setSequence(i+1);step.setTitle(task.getString("title"));step.setStatus(task.getString("status"));steps.insert(step);} plan.setCurrentVersion(version);plan.setStatus("RUNNING");plan.setLastActiveAt(now);plans.updateById(plan); }
 @Override public void markPaused(String runId,String reason){ updateStatus(runId,"PAUSED",reason); } @Override public void markRunning(String runId){updateStatus(runId,"RUNNING",null);} private void updateStatus(String runId,String status,String reason){AgentRunPlan p=plans.selectOne(Wrappers.lambdaQuery(AgentRunPlan.class).eq(AgentRunPlan::getRunId,runId));if(p!=null){p.setStatus(status);p.setPauseReason(reason);p.setLastActiveAt(System.currentTimeMillis());plans.updateById(p);}}
 @Override public AgentRunPlanVo detail(String runId){AgentRunPlan p=plans.selectOne(Wrappers.lambdaQuery(AgentRunPlan.class).eq(AgentRunPlan::getRunId,runId));if(p==null)return null;AgentRunPlanVo vo=new AgentRunPlanVo();vo.setRunId(runId);vo.setStatus(p.getStatus());vo.setPauseReason(p.getPauseReason());vo.setCurrentVersion(p.getCurrentVersion());vo.setCurrentStepId(p.getCurrentStepId());vo.setLastActiveAt(p.getLastActiveAt());vo.setVersions(versions.selectList(Wrappers.lambdaQuery(AgentRunPlanVersion.class).eq(AgentRunPlanVersion::getPlanId,p.getId()).orderByAsc(AgentRunPlanVersion::getVersion)).stream().map(v->{AgentRunPlanVo.Version x=new AgentRunPlanVo.Version();x.setVersion(v.getVersion());x.setReason(v.getReason());x.setSummary(v.getSummary());x.setSteps(steps.selectList(Wrappers.lambdaQuery(AgentRunPlanStep.class).eq(AgentRunPlanStep::getPlanVersionId,v.getId()).orderByAsc(AgentRunPlanStep::getSequence)).stream().map(s->{AgentRunPlanVo.Step y=new AgentRunPlanVo.Step();y.setId(s.getId());y.setStepKey(s.getStepKey());y.setSequence(s.getSequence());y.setTitle(s.getTitle());y.setStatus(s.getStatus());y.setResultSummary(s.getResultSummary());y.setAttemptCount(s.getAttemptCount());y.setStartedAt(s.getStartedAt());y.setCompletedAt(s.getCompletedAt());return y;}).collect(Collectors.toList()));return x;}).collect(Collectors.toList()));return vo;}
}
